skinparam dpi 170
skinparam backgroundColor #FFFFFF
skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 12
skinparam shadowing false
skinparam roundCorner 8
skinparam ArrowColor #333333
skinparam ArrowThickness 1.1
skinparam DefaultTextAlignment center
